apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgC0+O/ux7MkQhnU3Jk...YOUR_ENCRYPTED_DATA_HERE...
  template:
    metadata:
      name: mysecret
      namespace: default
